version: '3.8'

services:
  api:
    container_name: cofrecash-api
    image: node:20-alpine
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - "./:/app"

  db:
    container_name: cofrecash-db
    image: mysql
    restart: always
    env_file: .env
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3305"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cofrecash
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    