version: '3.8'

services:
  cofrecash-api:
    container_name: cofrecash-api
    image: node:19
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - "./:/app"